### ISSUE TITLE
https://github.com/isaacs/github/issues/66#issuecomment-734077419

### ISSUE THREAD

**Issue by copremesis** [danbulant/sketchware-docs#6]
why the thumbsdown on darkreader?

**Comment by danbulant** [comment]
Repos shouldn't be used as DMs.

As for the thumbsdown, that's because using an extension is a workaround and you shouldn't promote extensions there. I use dark mode on github as well but not dark reader, I use Stylus which allows me to load custom css styles.

**Comment by copremesis** [comment]
Wasn't a promotion just a comment...thanks for reply
